In [7]:
import torch

X = torch.tensor([[1.0, 4.0, 7.0], [2.0, 3.0, 6.0]], dtype=torch.float64)
X

tensor([[1., 4., 7.],
        [2., 3., 6.]], dtype=torch.float64)

In [15]:
X @ X.T

tensor([[66., 56.],
        [56., 49.]], dtype=torch.float64)

In [23]:
import numpy as np

torch.Tensor(np.array([[1.0, 4.0, 7.0], [2.0, 3.0, 6]])).dtype

torch.float32

In [ ]:
X[:, 1] = -99

tensor([[ 1., 99.,  7.],
        [ 2., 99.,  6.]], dtype=torch.float64)